FROM python:3.9-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://gitlab.com/Dysmon/simple_api.git /app

FROM python:3.9-alpine

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn
COPY --from=builder /app /app
ENTRYPOINT ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port $PORT"]
