#!/bin/bash

docker network create kafka-net

docker run -d \
  --name zookeeper \
  --network kafka-net \
  -e ZOOKEEPER_CLIENT_PORT=2181 \
  -e KAFKA_OPTS="-Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider" \
  -v ./zookeeper_jaas.conf:/etc/kafka/secrets/zookeeper_jaas.conf \
  -p 2181:2181 \
  confluentinc/cp-zookeeper:7.3.0


docker run -d \
  --name kafka-1 \
  --network kafka-net \
  -p 9092:9092 -p 29092:29092 \
  -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-1:19092,EXTERNAL://127.0.0.1:9092,DOCKER://host.docker.internal:29092 \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,DOCKER:SASL_PLAINTEXT \
  -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL \
  -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
  -e KAFKA_BROKER_ID=1 \
  -e KAFKA_OPTS="-Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf" \
  -e KAFKA_SASL_ENABLED_MECHANISMS=PLAIN \
  -e KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN \
  -e KAFKA_ZOOKEEPER_SET_ACL="true" \
  -e KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer \
  -e KAFKA_SUPER_USERS="User:broker;User:admin" \
  -v ./broker_jaas.conf:/etc/kafka/secrets/broker_jaas.conf \
  -v ./client.properties:/tmp/client.properties \
  confluentinc/cp-kafka:7.3.0

docker run -d \
  --name kafka-2 \
  --network kafka-net \
  -p 9093:9093 -p 29093:29093 \
  -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2:19093,EXTERNAL://127.0.0.1:9093,DOCKER://host.docker.internal:29093 \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,DOCKER:SASL_PLAINTEXT \
  -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL \
  -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
  -e KAFKA_BROKER_ID=2 \
  -e KAFKA_OPTS="-Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf" \
  -e KAFKA_SASL_ENABLED_MECHANISMS=PLAIN \
  -e KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN \
  -e KAFKA_ZOOKEEPER_SET_ACL="true" \
  -e KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer \
  -e KAFKA_SUPER_USERS="User:broker;User:admin" \
  -v ./broker_jaas.conf:/etc/kafka/secrets/broker_jaas.conf \
  confluentinc/cp-kafka:7.3.0

docker run -d \
  --name kafka-3 \
  --network kafka-net \
  -p 9094:9094 -p 29094:29094 \
  -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-3:19094,EXTERNAL://127.0.0.1:9094,DOCKER://host.docker.internal:29094 \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,DOCKER:SASL_PLAINTEXT \
  -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL \
  -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
  -e KAFKA_BROKER_ID=3 \
  -e KAFKA_OPTS="-Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf" \
  -e KAFKA_SASL_ENABLED_MECHANISMS=PLAIN \
  -e KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN \
  -e KAFKA_ZOOKEEPER_SET_ACL="true" \
  -e KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer \
  -e KAFKA_SUPER_USERS="User:broker;User:admin" \
  -v ./broker_jaas.conf:/etc/kafka/secrets/broker_jaas.conf \
  confluentinc/cp-kafka:7.3.0


