#!/bin/bash

docker network create kafka-net

docker run -d \
  --name zookeeper \
  --network kafka-net \
  -e ZOOKEEPER_CLIENT_PORT=2181 \
  -e ZOOKEEPER_SERVER_ID=1 \
  -p 2181:2181 \
  confluentinc/cp-zookeeper:7.3.0

docker run -d \
  --name kafka-1 \
  --network kafka-net \
  -p 9092:9092 \
  -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-1:19092,EXTERNAL://127.0.0.1:9092 \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT \
  -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL \
  -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
  -e KAFKA_BROKER_ID=1 \
  confluentinc/cp-kafka:7.3.0

docker run -d \
  --name kafka-2 \
  --network kafka-net \
  -p 9093:9093 \
  -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2:19093,EXTERNAL://127.0.0.1:9093 \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT \
  -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL \
  -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
  -e KAFKA_BROKER_ID=2 \
  confluentinc/cp-kafka:7.3.0

docker run -d \
  --name kafka-3 \
  --network kafka-net \
  -p 9094:9094 \
  -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-3:19094,EXTERNAL://127.0.0.1:9094 \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT \
  -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL \
  -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
  -e KAFKA_BROKER_ID=3 \
  confluentinc/cp-kafka:7.3.0

